//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWebZapateria.ServiciosZapateria {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoNegocio", Namespace="http://schemas.datacontract.org/2004/07/Negocio")]
    [System.SerializableAttribute()]
    public partial class ProductoNegocio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombre_productoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int precioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ultima_modificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre_producto {
            get {
                return this.nombre_productoField;
            }
            set {
                if ((object.ReferenceEquals(this.nombre_productoField, value) != true)) {
                    this.nombre_productoField = value;
                    this.RaisePropertyChanged("nombre_producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int precio {
            get {
                return this.precioField;
            }
            set {
                if ((this.precioField.Equals(value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ultima_modificacion {
            get {
                return this.ultima_modificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ultima_modificacionField, value) != true)) {
                    this.ultima_modificacionField = value;
                    this.RaisePropertyChanged("ultima_modificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosZapateria.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IngresarProducto", ReplyAction="http://tempuri.org/IService1/IngresarProductoResponse")]
        bool IngresarProducto(int id, string nombre_producto, string descripcion, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IngresarProducto", ReplyAction="http://tempuri.org/IService1/IngresarProductoResponse")]
        System.Threading.Tasks.Task<bool> IngresarProductoAsync(int id, string nombre_producto, string descripcion, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Validar", ReplyAction="http://tempuri.org/IService1/ValidarResponse")]
        bool Validar(string usuario, string contrasenna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Validar", ReplyAction="http://tempuri.org/IService1/ValidarResponse")]
        System.Threading.Tasks.Task<bool> ValidarAsync(string usuario, string contrasenna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerTodo", ReplyAction="http://tempuri.org/IService1/TraerTodoResponse")]
        AppWebZapateria.ServiciosZapateria.ProductoNegocio[] TraerTodo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TraerTodo", ReplyAction="http://tempuri.org/IService1/TraerTodoResponse")]
        System.Threading.Tasks.Task<AppWebZapateria.ServiciosZapateria.ProductoNegocio[]> TraerTodoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : AppWebZapateria.ServiciosZapateria.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<AppWebZapateria.ServiciosZapateria.IService1>, AppWebZapateria.ServiciosZapateria.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IngresarProducto(int id, string nombre_producto, string descripcion, int precio) {
            return base.Channel.IngresarProducto(id, nombre_producto, descripcion, precio);
        }
        
        public System.Threading.Tasks.Task<bool> IngresarProductoAsync(int id, string nombre_producto, string descripcion, int precio) {
            return base.Channel.IngresarProductoAsync(id, nombre_producto, descripcion, precio);
        }
        
        public bool Validar(string usuario, string contrasenna) {
            return base.Channel.Validar(usuario, contrasenna);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarAsync(string usuario, string contrasenna) {
            return base.Channel.ValidarAsync(usuario, contrasenna);
        }
        
        public AppWebZapateria.ServiciosZapateria.ProductoNegocio[] TraerTodo() {
            return base.Channel.TraerTodo();
        }
        
        public System.Threading.Tasks.Task<AppWebZapateria.ServiciosZapateria.ProductoNegocio[]> TraerTodoAsync() {
            return base.Channel.TraerTodoAsync();
        }
    }
}
